### PR TITLE
Update dhcpgui.pyw

### PR DESCRIPTION
**Pull request by joshhazelhurst123**
https://stackoverflow.com/questions/19646752/python-scrollbar-on-text-widget

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, you cannot just copy text in. Please run the program and make sure that it still works.

tip: Adding lines one by one and adapting them is one way to go about this.

**Comment by joshhazelhurst123** [comment]
Thanks @niccokunzmann for the feedback.

- I have reviewed my work, and I have a working vertical and horizontal slider on my workstation. I really need to read the stackoverflow discussion below to really understand what was going on.  https://stackoverflow.com/questions/19646752/python-scrollbar-on-text-widget
- Could you review this when you are able to. 

Basically on my machine, when I run dhcpgui I can see a slider that goes up and down and another slider that goes left to right, horizontal and vertical. 

Thanks.

**Comment by joshhazelhurst123** [comment]
[screenshots.docx](https://github.com/niccokunzmann/python_dhcp_server/files/15382930/screenshots.docx)

ok great, thanks @niccokunzmann review the document and let me know. Happy to discuss further.

**Comment by niccokunzmann** [comment]
You should be able to directly copy & paste the pictures into the comment text field.

grafik
grafik
grafik

Thanks! This looks good!

**Comment by joshhazelhurst123** [comment]
ah yes I see. Thank you @niccokunzmann that's great news.

**Pull request merged**
